### ISSUE TITLE
No code

### ISSUE THREAD

**Issue by Shakyamuni177te** [wavepot/wavepot#2]
There is no code in the wavepot.com repository and the website appears to be broken.

**Comment by jhermsmeier** [comment]
The website works for me, maybe just a temporary issue (i.e. instance spin up, because of long inactivity)?

**Comment by Shakyamuni177te** [comment]
Is it in any way dependent on the client-side secure key for functionality?

**Comment by jhermsmeier** [comment]
What you mean with the client-side secure key? And what exactly doesn't work for you on the website?

**Comment by Shakyamuni177te** [comment]
Altering the code doesn't appear to alter the sound. Also I changed a sin wave to a saw wave and it did nothing.

**Comment by stagas** [comment]
wavepot is under a (very slow) rewrite because of performance issues. The new [engine](https://github.com/wavepot/live) is somewhat ready and I'm currently working on the new [editor](https://github.com/wavepot/editor).

**Comment by Shakyamuni177te** [comment]
Wavepot in amazing. I want it to be the way it was when AaronNGrey showed it to me.

**Comment by Shakyamuni177te** [comment]
Your new version is rubbish. I'm making a new one so it's like how it used
to be.

**Comment by zeffii** [comment]
@Shakyamuni177te 
> Your new version is rubbish.

statements like that don't really help.. and aren't specific :)

**Comment by Shakyamuni177te** [comment]
I don't like the sound it makes anymore.

**Comment by stagas** [comment]
He's right. It is rubbish. That's why I'm doing the rewrite.

**Comment by Shakyamuni177te** [comment]
it used to be good

On 5 September 2015 at 14:05, stagas <notifications@github.com> wrote:

> He's right. It is rubbish. That's why I'm doing the rewrite.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/wavepot/wavepot/issues/2#issuecomment-137952537>.
>



-- 
Deer Simulator
https://www.facebook.com/pages/Deer-Simulator/1624237021193761
<https://github.com/Shakyamuni177te/The-Order-of-the-Mouse>

**Comment by stagas** [comment]
[enjoy!](https://github.com/wavepot/wavep0t)

**Comment by cheery** [comment]
Awesome! Thank you stagas. Now we can work on it too. ^^

**Comment by stagas** [comment]
Note that some components have changes in-place and I don't remember which, so a new install might fail, which is why I have checked in everything.
