### ISSUE TITLE
How to import sound from another website?

### ISSUE THREAD

**Issue by AnastasiaDunbar** [wavepot/wavepot#3]
`import sound from 'http://www.w3schools.com/html/horse.mp3';` for example.

**Comment by stagas** [comment]
Not possible right now :( only github
I'll try to make it work though as soon as I get the build running locally, haven't touched it in ages and it's giving me some pain for unknown reasons. I'll post an update in this thread when it's done.

**Comment by stagas** [comment]
Should be working now:
http://wavepot.com/stagas/c06b3f2a28550cf624b47444f00584e0

But you can only load wav files and only from places where they allow cross origin requests. So if you need random URLs from the web then you'd probably need to setup a proxy to download and serve with proper headers. Enjoy!

**Comment by stagas** [comment]
In the latest implementation (https://github.com/wavepot/wavepot/tree/v3) you can use the `fetch-sample` library to ask the main thread to `fetch()` and `decodeAudioData()`  to a `Floats32Array` that you can use directly into your dsp function.
See https://github.com/wavepot/wavepot/blob/v3/drumbeats.js#L2 and https://github.com/wavepot/wavepot/blob/v3/drumbeats.js#L14 - wavs, mp3s and anything that can be fetched and decoded by the AudioContext can be used for samples.

**Comment by stagas** [comment]
Closing because is solved in https://github.com/wavepot/wavepot/tree/v3
